# env:
#   node: true
#   es2021: true
extends:
  - eslint:recommended
  # - airbnb-base
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
# parserOptions:
#   ecmaVersion: 12
#   sourceType: module
plugins:
  - simple-import-sort
rules:
  simple-import-sort/imports: error
  simple-import-sort/exports: error
