version: "3.8"
services:
  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - ./db:/var/lib/postgresql/data
      # - "./seed/base.sql:/docker-entrypoint-initdb.d/seed.sql"
